#!/bin/bash
if [ $# -eq 0 ]; then
  echo "usage:"
  echo "   build macos"
  echo "  or"
  echo "   build linux"
  exit 1
fi

os=$1

if [ $os == "macos" ]; then
  echo "building for macos"
  gcc -std=c99 -Wall -Wextra -lm src/*.c -framework Accelerate -o run/ghf
elif [ $os == "linux" ]; then
  echo "building for linux"
  gcc -std=c99 -g -ggdb -Wall -Wextra -lm -llapacke -llapack src/*.c -o run/ghf
else
  echo "tell me how to build on $os"
  exit 1
fi
